export const AUTH_COPY = {
  welcomeBack: 'Welcome back',
  signInSubtitle: 'Sign in with your phone — we’ll text you a code.',
  sendCode: 'Send code',
  orContinueWith: 'or continue with',
  apple: 'Apple',
  google: 'Google',
  newHere: 'New here?',
  createAccount: 'Create account',
  continueAsGuest: 'Continue as guest →',
  phonePlaceholder: '50 555 0134',
  signUpTitle: 'Create account',
  signUpSubtitle: 'Save your usual order and check out faster.',
  fullName: 'Full name',
  phone: 'Phone',
  email: 'Email',
  emailOptional: '· Optional',
  namePlaceholder: 'Aisha Khalid',
  emailPlaceholder: 'aisha@example.com',
  whatsappOffers: 'Send me offers and new menu drops on WhatsApp',
  createAccountCta: 'Create account',
  termsPrefix: 'By continuing you agree to the ',
  terms: 'Terms',
  and: ' and ',
  privacy: 'Privacy Policy',
  verifyTitle: 'Enter the code',
  verifySubtitle: (phone: string) =>
    `We sent a 4-digit code to ${phone}. It expires in a few minutes.`,
  verifyCta: 'Verify & continue',
  resend: 'Resend code',
  changeNumber: 'Change number',
} as const;

export const MENU_COPY = {
  pickupLabel: 'Pickup · Al Satwa',
  eta: '15 min',
  searchPlaceholder: 'Search shawarma, broasted, manakish…',
  viewCart: 'View cart',
  comboBadge: '🔥 Combo of the week',
  bestSeller: 'Best seller',
} as const;
